### ISSUE TITLE
401, Unauthorized

### ISSUE THREAD

**Issue by leon1995** [nborrmann/jodel_api#26]
when I try to make an API call, I get
`401, 'Unauthorized`

Last API call was about 3 hours ago

EDIT: i tried it from different accounts. did not help. seems like, 401 is an ip ban? but I didnt even posted much. do you know why?

EDIT: tried the same account on different device. same error :/

EDIT: different account on the same divice got no error. seems like the account got banned

**Comment by nborrmann** [comment]
I think 401 means outdated `access_token`, you need to refresh it, as written in the readme. I'll add the status code to the readme as well.

**Comment by gaurav-stepin** [comment]
Hi Nborrmann,
I got the same issue. I have studied documentation also. It rightly suggests refresh token. But the issue is that as token is expired I can't create object of jodel api so can't refresh tokens. Here is the code.
jodel = jodel_api.JodelAccount(params ....); // this will fail as I have expired token.
jodel.refresh_all_tokens();
Am I missing something here?
Many Thanks

**Comment by nborrmann** [comment]
Add ``update_location=False`` to the constructor and it won't make any requests so it can't fail.

**Comment by gaurav-stepin** [comment]
Hi Nborrmann,
That was wonderfull help.
Many thanks
